version: "2.4"

services:
  api:
    build: .
    environment:
      PORT: 
      PG_CONNECTION_STRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "${PORT}:${PORT}"

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER:
      POSTGRES_DB: 
      POSTGRES_PORT: 
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 5432:5432
