version: "2.4"

services:

  api:
    container_name: api
    build: .
    environment:
      PORT: 
      PG_CONNECTION_STRING:
    ports:
      - "${PORT}:${PORT}"

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRESS_PASSWORD: 
      POSTGRESS_USER:
      POSTGRESS_DB: 
      POSTGRES_HOST_AUTH_METHOD: 'trust'
