version: "2.4"

services:
  api:
    build: .
    environment:
      PORT: 
      PG_CONNECTION_STRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "3000:3000"

  db:
    container_name: postgres
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER:
      POSTGRES_DB: 
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
