name: CI

on:
  push:
    branches: [ main ]

env: 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: J0PP3
  POSTGRES_DB: postgres
  POSTGRES_PORT: 5432


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: docker-compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: publish
        run: docker-compose push
